SQLPLUS /NOLOG
CONN /AS SYSDBA
SELECT USERNAME FROM DBA_USERS WHERE USERNAME = 'ANA';
SELECT USERNAME FROM DBA_USERS WHERE USERNAME = 'ELENA';
SELECT USERNAME FROM DBA_USERS WHERE USERNAME = 'FER';
 SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE='ANA';
 SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE='SYSTEM';
 

 SELECT * FROM DBA_ROLES;
 SELECT * FROM DBA_ROLES WHERE ROLE='VENDEDOR';
 SELECT * FROM DBA_ROLES WHERE ROLE='ROLE_VENDEDOR';
 SELECT * FROM DBA_ROLES WHERE ROLE='ROLE_CLIENTE';
 
 SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE='ANA'
  GRANT DBA TO ANA;
  SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE='ANA';
  SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE='ANA';
  
  
   CONN ANA/123;
   CREATE ROLE ROLE_VENDEDOR;
   CREATE ROLE ROLE_CLIENTE;
   GRANT ROLE_CLIENTE TO FER;
   GRANT ROLE_VENDEDOR TO ELENA;
   
   SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE='ELENA';
   SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE='FER';
   
   SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE='FER';
   SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE='ELENA';
   
   SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE='FER';
   SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE='ELENA';
   
   SELECT * FROM ROLE_SYS_PRIVS WHERE ROLE='ROLE_VENDEDOR';
   SELECT * FROM ROLE_SYS_PRIVS WHERE ROLE='ROLE_CLIENTE';
   
   
   CONN BENITO/123;
   SELECT TABLE_NAME FROM USER_TABLES;
   GRANT SELECT ON ESTUDIANTE TO ROLE_VENDEDOR;
   GRANT INSERT ON ESTUDIANTE TO ROLE_CLIENTE;
   
   SELECT * FROM DBA_ROLE_PRIVS;
	SELECT * FROM USER_ROLE_PRIVS;
	SELECT * FROM DBA_ROLES;
	
	CONN ELENA/123
	SELECT * FROM USER_ROLE_PRIVS;
	SELECT * FROM ROLE_SYS_PRIVS WHERE ROLE='ROLE_CLIENTE';
	SELECT * FROM ROLE_SYS_PRIVS WHERE ROLE='ROLE_VENDEDOR';
	SELECT * FROM ROLE_TAB_PRIVS WHERE ROLE='ROLE_VENDEDOR';
	SELECT * FROM ROLE_TAB_PRIVS WHERE ROLE='ROLE_CLIENTE';
   
   CONN FER/123
	SELECT * FROM USER_ROLE_PRIVS;
	SELECT * FROM ROLE_SYS_PRIVS WHERE ROLE='ROLE_CLIENTE';
	SELECT * FROM ROLE_SYS_PRIVS WHERE ROLE='ROLE_VENDEDOR';
	SELECT * FROM ROLE_TAB_PRIVS WHERE ROLE='ROLE_VENDEDOR';
	SELECT * FROM ROLE_TAB_PRIVS WHERE ROLE='ROLE_CLIENTE';
   
   INSERT INTO BENITO.ESTUDIANTE VALUES ('MARIA',12);
   
   CONN ANA/123
   REVOKE CREATE SESSION FROM FER;
   REVOKE CREATE SESSION FROM ELENA;
   CONN ELENA/123
   
   CONN ANA/123
   REVOKE CREATE SESSION FROM ROLE_CLIENTE;
   REVOKE CREATE SESSION FROM ROLE_VENDEDOR;
   REVOKE CONNECT FROM ROLE_CLIENTE;
   REVOKE INSERT ON BENITO.ESTUDIANTE FROM ROLE_VENDEDOR;
   REVOKE SELECT ON BENITO.ESTUDIANTE FROM ROLE_VENDEDOR;
   
   CONN BENITO/123
   REVOKE SELECT ON ESTUDIANTE FROM ROLE_VENDEDOR;
    CONN ANA/123
	SELECT * FROM ROLE_ROLE_PRIVS WHERE ROLE='ROLE_VENDEDOR';
	DROP ROLE ROLE_VENDEDOR;
	