
SQLPLUS /NOLOG
CONN /AS SYSDBA

SELECT USERNAME FROM DBA_USERS WHERE USERNAME LIKE '%ANA%';
SELECT USERNAME FROM DBA_USERS WHERE USERNAME LIKE '%BENITO%';
SELECT USERNAME FROM DBA_USERS WHERE USERNAME LIKE '%CAROL%';

SELECT * FROM DBA_SYS_PRIVS;
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE LIKE '%ANA%';
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE LIKE 'BENITO';
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'CAROL';

SELECT * FROM DBA_TAB_PRIVS;
SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE LIKE '%ANA%';
SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE LIKE '%BENITO%';
SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE LIKE '%CAROL%';

CONN ANA/123
SELECT TABLE_NAME FROM USER_TABLES;
SELECT * FROM estudiante;
INSERT INTO estudiante VALUES ('JUAN',2);
INSERT INTO estudiante VALUES ('MARIA');
INSERT INTO estudiante VALUES ('PEDRO');
UPDATE estudiante SET NOMBRE ='JUANITO' WHERE NOMBRE='JUAN';
DELETE FROM estudiante WHERE NOMBRE='JUAN';
DELETE FROM estudiante WHERE NOMBRE='JUANITO';

CONN BENITO/123
SELECT TABLE_NAME FROM USER_TABLES;
INSERT INTO estudiante VALUES ('JUAN');
INSERT INTO ANA.estudiante VALUES ('JUAN');

CONN ANA/123
GRANT INSERT ON estudiante TO BENITO;
SELECT * FROM USER_TAB_PRIVS WHERE GRANTEE LIKE '%ANA%';
SELECT * FROM USER_TAB_PRIVS WHERE GRANTEE LIKE '%BENITO%';





CONN BENITO/123
INSERT INTO estudiante VALUES ('JUAN');
INSERT INTO ANA.estudiante VALUES ('JUAN');
SELECT * FROM ANA.estudiante;
SELECT TABLE_NAME FROM USER_TABLES;

SELECT * FROM USER_TAB_PRIVS WHERE GRANTOR LIKE '%BENITO%';
GRANT SELECT, INSERT ON ESTUDIANTE TO ANA
SELECT * FROM USER_TAB_PRIVS WHERE GRANTOR LIKE '%BENITO%';
SELECT * FROM USER_TAB_PRIVS WHERE GRANTEE LIKE '%ANA%';
GRANT DELETE, UPDATE ON ESTUDIANTE TO  ANA WITH GRANT OPTION;
SELECT * FROM USER_TAB_PRIVS WHERE GRANTEE LIKE '%ANA%';


CONN ANA/123
SELECT * FROM ESTUDIANTE;
SELECT * FROM BENITO.ESTUDIANTE;
INSERT INTO BENITO.ESTUDIANTE VALUES ('JUAN',15)

CONN /AS SYSDBA
ALTER USER BENITO QUOTA 1M ON USERS;
SELECT * FROM USER_TAB_PRIVS WHERE GRANTEE LIKE '%ANA%';
SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE LIKE '%ANA%';
INSERT INTO BENITO.ESTUDIANTE VALUES ('JUAN',15);


CONN ANA/123
GRANT UPDATE ON BENITO.ESTUDIANTE TO CAROL;
INSERT INTO BENITO.ESTUDIANTE VALUES ('JUAN',15);

CONN CAROL/123
SELECT * FROM USER_TAB_PRIVS WHERE GRANTEE LIKE '%ANA%';
SELECT TABLE_NAME FROM USER_TABLES;
INSERT INTO BENITO.ESTUDIANTE VALUES ('JUAN',15);
INSERT INTO ESTUDIANTE VALUES ('JUAN',15);
SELECT * FROM ESTUDIANTE;
SELECT * FROM USER_TAB_PRIVS WHERE GRANTOR LIKE '%ANA%';
SELECT * FROM USER_TAB_PRIVS WHERE OWNER LIKE '%BENITO%';