sqlplus /nolog
CONN /AS SYSDBA
SELECT USERNAME FROMDBA_USERS WHERE USERNAME='ESCUELA';
CONN ESCUELA/123
SELECT TABLE_NAME FROM USER_TABLES;

CREATE TABLE PROFESOR(
	NOMBRE VARCHAR2(30) CONSTRAINT PRO_NOMBRE_NN NOT NULL,
	SEXO CHAR(1) DEFAULT 'F' CONSTRAINT PRO_SEXO_CK CHECK(SEXO='F' OR SEXO='M',
	NOPROFESOR INT CONSTRAINT PRO_NOPROFESOR_PK PRIMARY KEY,
	SALARIO FLOAT DEFAULT 0 CONSTRAINT PRO_SALARIO_NN NOT NULL,
	FECHADEINGRESO DATE DEFAULT SYSDATE CONSTRAINT PRO_FECHADEINGRESO_NN NOT NULL
	);
INSERT INTO PROFESOR VALUES('JUAN','M',1,0,'27/10/2020')#INSERSION EN LA TABLA PROFESOR
INSERT INTO PROFESOR VALUES('JUAN',DEFAULT,2,DEFAULT,'27/10/2020')#INSERSION EN LA TABLA PROFESOR CON VALORES POR DEFECTO
INSERT INTO PROFESOR VALUES('JUAN',DEFAULT,2,DEFAULT,DEFAULT)#INSERSION EN LA TABLA PROFESOR CON VALORES POR DEFECTO
DESC PROFESOR;#DESCRIBE CAMPOS DE LA TABLA

SELECT *FROM USER_CONSTRAINTS;#CONSULTAR TABLAS DEL CONSTRAINT
SELECT CONSTRAINT_NME FROM USER_CONSTRAINTS;#CONSULTAR TABLA DE CONSTRAINT NOMBRE


CREATE TABLE ASIGNATURA(
	NOMBRE CHAR(3),
	CREDITOS VARCHAR2(25),
	NOPROFESOR CHAR(25),
	CLAVE NUMBER(8,0),
	);

CREATE TABLE GRUPO(
	CLAVE CHAR(3),
	NOPROFESOR CHAR(25),
	NOGRUPO CHAR(25),
	);

